baseURL: 'https://dgpalmieri.github.io/'
languageCode: 'en-us'
title: 'dylan palmieri'
theme: 'hugo-coder'

menu:
    main:
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 2
    - identifier: photography
      name: Photography
      title: Photography
      url: /photography/
      weight: 1
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 0

params:
    author: "Dylan Palmieri"
    info: "Software Engineer"
    since: "2021"
    colorScheme: "auto"
    hidecolorschemetoggle: False
    social:
      name: "Github"
      icon: "fa-brands fa-github fa-2x"
      weight: 1
      url: "https://github.com/dgpalmieri/"
