baseURL: 'https://dgpalmieri.github.io/'
languageCode: 'en-us'
title: 'dylan palmieri'
theme: 'anubis'

menu:
    main:
    - identifier: archive
      name: Archive
      title: Archive
      url: /posts/
      weight: 0

params:
    style: dark
