baseURL: 'https://dgpalmieri.github.io/'
languageCode: 'en-us'
title: 'dylan palmieri'
theme: 'anubis'

menu:
    main:
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 0
    - identifier: photography
      name: Photography
      title: Photography
      url: /photography/
      weight: 1
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 2

params:
    author: "Dylan Palmieri"
    style: dark
